@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

RestaurantDirectory *-right-> "1" UniqueRestaurantList

UniqueRestaurantList -right-> Restaurant

Restaurant *--> "1" Name
Restaurant *--> "1" Phone
Restaurant *--> "0..1" Rating
Restaurant *--> "1" Address
Restaurant *--> "*" Tag
@enduml
