@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "RestaurantDirectory Storage" #F4F6F6{
Class "<<interface>>\nRestaurantDirectoryStorage" as RestaurantDirectoryStorage
Class JsonRestaurantDirectoryStorage
Class JsonSerializableRestaurantDirectory
Class JsonAdaptedRestaurant
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" RestaurantDirectoryStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> RestaurantDirectoryStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonRestaurantDirectoryStorage .up.|> RestaurantDirectoryStorage
JsonRestaurantDirectoryStorage ..> JsonSerializableRestaurantDirectory
JsonSerializableRestaurantDirectory --> "*" JsonAdaptedRestaurant
JsonAdaptedRestaurant --> "*" JsonAdaptedTag

@enduml
