@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedRestaurantDirectory" as VersionedRestaurantDirectory MODEL_COLOR
end box

[-> Model : undoRestaurantDirectory()
activate Model

Model -> VersionedRestaurantDirectory : undo()
activate VersionedRestaurantDirectory

VersionedRestaurantDirectory -> VersionedRestaurantDirectory :resetData(ReadOnlyRestaurantDirectory)
VersionedRestaurantDirectory --> Model :
deactivate VersionedRestaurantDirectory

[<-- Model
deactivate Model

@enduml
