@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":RestaurantDirectoryParser" as rdp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> rdp ++: parseCommand(commandText)
create ecp
rdp -> ecp
rdp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editRestaurantDescriptor
ec --> ecp --
ecp --> rdp --: command
rdp --> logic --: command

@enduml
